name: WorldReset
main: ss.linearlogic.worldreset.WorldReset
author: LinearLogic
version: 1.4.1
commands:
    worldreset:
        description: Root command
        usage: /wr [args]
        aliases: [wr, resetworld, resetworlds]
permissions:
    resetworld.reset:
        description: Permission to schedule a world reset, including via '/wr reset now'
        default: false